=begin
Insightly API v2.2

OpenAPI spec version: v2.2

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TaskCategoriesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TaskCategoriesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TaskCategoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TaskCategoriesApi' do
    it 'should create an instact of TaskCategoriesApi' do
      @instance.should be_a(SwaggerClient::TaskCategoriesApi)
    end
  end

  # unit tests for add_task_category
  # Adds a Task Category
  # This endpoint is used to create a new task category. This endpoint is only accessible to users with administrator permission.
  # @param category The Task Category to add (just include JSON object as request body)
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20018]
  describe 'add_task_category test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for delete_task_category
  # Deactivates a Task Category
  # This endpoint is used to deactivate a task category. This endpoint is only accessible to users with administrator permission.
  # @param id A Task Category&#39;s ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_task_category test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for get_task_categories
  # Gets a list of Task Categories
  # This read only endpoint returns a list of the task categories set up for the Insightly instance.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :skip Optional, number of records to skip.
  # @option opts [Integer] :top Optional, maximum number of records to return in the response.
  # @option opts [BOOLEAN] :count_total Optional, true if total number of records should be returned in the response headers.
  # @return [Array<InlineResponse20018>]
  describe 'get_task_categories test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for get_task_category
  # Gets a Task Category
  # This endpoint returns the graph for a specific task category.
  # @param id A Task Category&#39;s ID
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20018]
  describe 'get_task_category test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for update_task_category
  # Updates a Task Category
  # This endpoint is used to update an existing task category, for example to change the background color for the task category&#39;s label in the web UI. This endpoint is only accessible to users with administrator permission.
  # @param category A Task Category (just include JSON object as request body)
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20018]
  describe 'update_task_category test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
