=begin
Insightly API v2.2

OpenAPI spec version: v2.2

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TeamMembersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TeamMembersApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TeamMembersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TeamMembersApi' do
    it 'should create an instact of TeamMembersApi' do
      @instance.should be_a(SwaggerClient::TeamMembersApi)
    end
  end

  # unit tests for add_team_member
  # Adds a new Team Member
  # 
  # @param api_team_member The Team Member to add (just include JSON object as request body)
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20035]
  describe 'add_team_member test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for delete_team_member
  # Deletes a Team Member
  # 
  # @param id A Team Member&#39;s ID (PERMISSION_ID)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_team_member test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for get_team_member
  # Gets a Team Member
  # 
  # @param id A Team Member&#39;s ID (PERMISSION_ID)
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20035]
  describe 'get_team_member test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for get_team_members
  # Gets a list of Team Members
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :skip Optional, number of team members to skip.
  # @option opts [Integer] :top Optional, maximum number of team members to return in the response.
  # @option opts [BOOLEAN] :count_total Optional, true if total number of records should be returned in the response headers.
  # @return [Array<InlineResponse20035>]
  describe 'get_team_members test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for update_team_member
  # Updates a Team Member
  # 
  # @param api_team_member The Team Member to update (just include JSON object as request body)
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20035]
  describe 'update_team_member test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
