=begin
Insightly API v2.2

OpenAPI spec version: v2.2

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::APICustomFieldOption
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'APICustomFieldOption' do
  before do
    # run before each test
    @instance = SwaggerClient::APICustomFieldOption.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of APICustomFieldOption' do
    it 'should create an instact of APICustomFieldOption' do
      @instance.should be_a(SwaggerClient::APICustomFieldOption) 
    end
  end
  describe 'test attribute "option_id"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "option_value"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "option_default"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

