=begin
Insightly API v2.2

OpenAPI spec version: v2.2

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::APILinkEmailAddress
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'APILinkEmailAddress' do
  before do
    # run before each test
    @instance = SwaggerClient::APILinkEmailAddress.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of APILinkEmailAddress' do
    it 'should create an instact of APILinkEmailAddress' do
      @instance.should be_a(SwaggerClient::APILinkEmailAddress) 
    end
  end
  describe 'test attribute "email"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

