=begin
Insightly API v2.2

OpenAPI spec version: v2.2

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module SwaggerClient
  # APIOpportunity
  class InlineResponse20025
    # Set of Links attached to the Opportunity
    attr_accessor :links

    # Duration of the bid of the Opportunity, if per hour/day/etc as an integer value
    attr_accessor :bid_duration

    # Opportunity details
    attr_accessor :opportunity_details

    # User ID of the record owner
    attr_accessor :owner_user_id

    # The Pipeline ID that the Opportunity is in, if it has been assigned to one. Note! This is a read-only field, to update the Pipeline please use the /Opportunities/{id}/Pipeline endpoint.
    attr_accessor :pipeline_id

    # Visible To: Everyone, Owner, Team or Individuals
    attr_accessor :visible_to

    # Set of Custom Fields attached to the Opportunity
    attr_accessor :customfields

    # Three character code for a currency
    attr_accessor :bid_currency

    # Name of the Opportunity
    attr_accessor :opportunity_name

    # Actual close date of the Opportunity, in YYYY-MM-DD format
    attr_accessor :actual_close_date

    # ID of the responsible user for the Opportunity
    attr_accessor :responsible_user_id

    # Set of Tags attached to the Opportunity
    attr_accessor :tags

    # Forecast close date of the Opportunity, in YYYY-MM-DD format
    attr_accessor :forecast_close_date

    # Opportunity State (required): Open, Abandoned, Lost, Suspended, Won
    attr_accessor :opportunity_state

    # The Category ID of the Opportunity, if it has been assigned to one
    attr_accessor :category_id

    # Unique ID for the Opportunity record
    attr_accessor :opportunity_id

    # Potential value of the Opportunity, as an integer value
    attr_accessor :bid_amount

    # The Stage ID of the Stage that the Opportunity is in, if it has been assigned to one. Note! This is a read-only field, to update the Pipeline Stage please use the /Opportunities/{id}/PipelineStage endpoint.
    attr_accessor :stage_id

    # If VISIBLE_TO is 'Team', the TEAM_ID
    attr_accessor :visible_team_id

    # Type of bid for the Opportunity: Fixed Bid, Per Hour, Per Day, Per Week, Per Month or Per Year
    attr_accessor :bid_type

    # If VISIBLE_TO is 'Individuals', a comma separated list of User IDs
    attr_accessor :visible_user_ids

    # URL of the Image for the Opportunity
    attr_accessor :image_url

    # Total value of the Opportunity, calculated based on BID_AMOUNT, BID_TYPE and BID_DURATION. This is a read-only field.
    attr_accessor :opportunity_value

    # Date and time Opportunity record created, as Coordinated Universal Time
    attr_accessor :date_created_utc

    # Percentage probability of winning the Opportunity, as an integer value from 0 to 100
    attr_accessor :probability

    # Opportunity State Reason ID. Optional, if specified this field must have a valid State Reason ID.
    attr_accessor :opportunity_state_reason_id

    # Date and time Opportunity record updated, as Coordinated Universal Time
    attr_accessor :date_updated_utc

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'links' => :'LINKS',
        
        :'bid_duration' => :'BID_DURATION',
        
        :'opportunity_details' => :'OPPORTUNITY_DETAILS',
        
        :'owner_user_id' => :'OWNER_USER_ID',
        
        :'pipeline_id' => :'PIPELINE_ID',
        
        :'visible_to' => :'VISIBLE_TO',
        
        :'customfields' => :'CUSTOMFIELDS',
        
        :'bid_currency' => :'BID_CURRENCY',
        
        :'opportunity_name' => :'OPPORTUNITY_NAME',
        
        :'actual_close_date' => :'ACTUAL_CLOSE_DATE',
        
        :'responsible_user_id' => :'RESPONSIBLE_USER_ID',
        
        :'tags' => :'TAGS',
        
        :'forecast_close_date' => :'FORECAST_CLOSE_DATE',
        
        :'opportunity_state' => :'OPPORTUNITY_STATE',
        
        :'category_id' => :'CATEGORY_ID',
        
        :'opportunity_id' => :'OPPORTUNITY_ID',
        
        :'bid_amount' => :'BID_AMOUNT',
        
        :'stage_id' => :'STAGE_ID',
        
        :'visible_team_id' => :'VISIBLE_TEAM_ID',
        
        :'bid_type' => :'BID_TYPE',
        
        :'visible_user_ids' => :'VISIBLE_USER_IDS',
        
        :'image_url' => :'IMAGE_URL',
        
        :'opportunity_value' => :'OPPORTUNITY_VALUE',
        
        :'date_created_utc' => :'DATE_CREATED_UTC',
        
        :'probability' => :'PROBABILITY',
        
        :'opportunity_state_reason_id' => :'OPPORTUNITY_STATE_REASON_ID',
        
        :'date_updated_utc' => :'DATE_UPDATED_UTC'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'links' => :'Array<APILink>',
        :'bid_duration' => :'Integer',
        :'opportunity_details' => :'String',
        :'owner_user_id' => :'Integer',
        :'pipeline_id' => :'Integer',
        :'visible_to' => :'String',
        :'customfields' => :'Array<APICustomField>',
        :'bid_currency' => :'String',
        :'opportunity_name' => :'String',
        :'actual_close_date' => :'DateTime',
        :'responsible_user_id' => :'Integer',
        :'tags' => :'Array<APITag>',
        :'forecast_close_date' => :'DateTime',
        :'opportunity_state' => :'String',
        :'category_id' => :'Integer',
        :'opportunity_id' => :'Integer',
        :'bid_amount' => :'Integer',
        :'stage_id' => :'Integer',
        :'visible_team_id' => :'Integer',
        :'bid_type' => :'String',
        :'visible_user_ids' => :'String',
        :'image_url' => :'String',
        :'opportunity_value' => :'Integer',
        :'date_created_utc' => :'DateTime',
        :'probability' => :'Integer',
        :'opportunity_state_reason_id' => :'Integer',
        :'date_updated_utc' => :'DateTime'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'LINKS']
        if (value = attributes[:'LINKS']).is_a?(Array)
          self.links = value
        end
      end
      
      if attributes[:'BID_DURATION']
        self.bid_duration = attributes[:'BID_DURATION']
      end
      
      if attributes[:'OPPORTUNITY_DETAILS']
        self.opportunity_details = attributes[:'OPPORTUNITY_DETAILS']
      end
      
      if attributes[:'OWNER_USER_ID']
        self.owner_user_id = attributes[:'OWNER_USER_ID']
      end
      
      if attributes[:'PIPELINE_ID']
        self.pipeline_id = attributes[:'PIPELINE_ID']
      end
      
      if attributes[:'VISIBLE_TO']
        self.visible_to = attributes[:'VISIBLE_TO']
      end
      
      if attributes[:'CUSTOMFIELDS']
        if (value = attributes[:'CUSTOMFIELDS']).is_a?(Array)
          self.customfields = value
        end
      end
      
      if attributes[:'BID_CURRENCY']
        self.bid_currency = attributes[:'BID_CURRENCY']
      end
      
      if attributes[:'OPPORTUNITY_NAME']
        self.opportunity_name = attributes[:'OPPORTUNITY_NAME']
      end
      
      if attributes[:'ACTUAL_CLOSE_DATE']
        self.actual_close_date = attributes[:'ACTUAL_CLOSE_DATE']
      end
      
      if attributes[:'RESPONSIBLE_USER_ID']
        self.responsible_user_id = attributes[:'RESPONSIBLE_USER_ID']
      end
      
      if attributes[:'TAGS']
        if (value = attributes[:'TAGS']).is_a?(Array)
          self.tags = value
        end
      end
      
      if attributes[:'FORECAST_CLOSE_DATE']
        self.forecast_close_date = attributes[:'FORECAST_CLOSE_DATE']
      end
      
      if attributes[:'OPPORTUNITY_STATE']
        self.opportunity_state = attributes[:'OPPORTUNITY_STATE']
      end
      
      if attributes[:'CATEGORY_ID']
        self.category_id = attributes[:'CATEGORY_ID']
      end
      
      if attributes[:'OPPORTUNITY_ID']
        self.opportunity_id = attributes[:'OPPORTUNITY_ID']
      end
      
      if attributes[:'BID_AMOUNT']
        self.bid_amount = attributes[:'BID_AMOUNT']
      end
      
      if attributes[:'STAGE_ID']
        self.stage_id = attributes[:'STAGE_ID']
      end
      
      if attributes[:'VISIBLE_TEAM_ID']
        self.visible_team_id = attributes[:'VISIBLE_TEAM_ID']
      end
      
      if attributes[:'BID_TYPE']
        self.bid_type = attributes[:'BID_TYPE']
      end
      
      if attributes[:'VISIBLE_USER_IDS']
        self.visible_user_ids = attributes[:'VISIBLE_USER_IDS']
      end
      
      if attributes[:'IMAGE_URL']
        self.image_url = attributes[:'IMAGE_URL']
      end
      
      if attributes[:'OPPORTUNITY_VALUE']
        self.opportunity_value = attributes[:'OPPORTUNITY_VALUE']
      end
      
      if attributes[:'DATE_CREATED_UTC']
        self.date_created_utc = attributes[:'DATE_CREATED_UTC']
      end
      
      if attributes[:'PROBABILITY']
        self.probability = attributes[:'PROBABILITY']
      end
      
      if attributes[:'OPPORTUNITY_STATE_REASON_ID']
        self.opportunity_state_reason_id = attributes[:'OPPORTUNITY_STATE_REASON_ID']
      end
      
      if attributes[:'DATE_UPDATED_UTC']
        self.date_updated_utc = attributes[:'DATE_UPDATED_UTC']
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          links == o.links &&
          bid_duration == o.bid_duration &&
          opportunity_details == o.opportunity_details &&
          owner_user_id == o.owner_user_id &&
          pipeline_id == o.pipeline_id &&
          visible_to == o.visible_to &&
          customfields == o.customfields &&
          bid_currency == o.bid_currency &&
          opportunity_name == o.opportunity_name &&
          actual_close_date == o.actual_close_date &&
          responsible_user_id == o.responsible_user_id &&
          tags == o.tags &&
          forecast_close_date == o.forecast_close_date &&
          opportunity_state == o.opportunity_state &&
          category_id == o.category_id &&
          opportunity_id == o.opportunity_id &&
          bid_amount == o.bid_amount &&
          stage_id == o.stage_id &&
          visible_team_id == o.visible_team_id &&
          bid_type == o.bid_type &&
          visible_user_ids == o.visible_user_ids &&
          image_url == o.image_url &&
          opportunity_value == o.opportunity_value &&
          date_created_utc == o.date_created_utc &&
          probability == o.probability &&
          opportunity_state_reason_id == o.opportunity_state_reason_id &&
          date_updated_utc == o.date_updated_utc
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [links, bid_duration, opportunity_details, owner_user_id, pipeline_id, visible_to, customfields, bid_currency, opportunity_name, actual_close_date, responsible_user_id, tags, forecast_close_date, opportunity_state, category_id, opportunity_id, bid_amount, stage_id, visible_team_id, bid_type, visible_user_ids, image_url, opportunity_value, date_created_utc, probability, opportunity_state_reason_id, date_updated_utc].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = SwaggerClient.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
